/* =====================================================================
   Static Chat — tips.js
   Fun tips, loading quotes, and silly splash-screen messages.
   ===================================================================== */

export const LOADING_TIPS = [
  // Static Chat real feature tips
  "💬 Right-click any message to reply, edit, pin, react, copy ID, or report it.",
  "📌 Pin important messages so the whole chat can find them later.",
  "😂 React to messages when words are too much work.",
  "↩️ Reply to a message so everyone knows exactly what chaos you are responding to.",
  "🔍 Use chat search to find old messages without scrolling through ancient history.",
  "🔎 Try filters like from:name, has:link, has:gif, has:reply, or has:pin.",
  "📋 Copy Message ID is useful for reports, receipts, and proving someone said 'brb' three hours ago.",
  "👤 Click someone's avatar or name to open their profile.",
  "📝 Friend notes are private. Finally, a place to remember who is who.",
  "🎭 The GIF picker is powered by Tenor — search anything you want.",
  "⭐ Favorite any GIF or emoji to save it for quick access later.",
  "🌙 Change your status from the bottom-left user panel.",
  "🟢 You can be online, idle, DND, invisible, or emotionally buffering.",
  "👻 Invisible means you appear offline, not that you become a ghost. Probably.",
  "⌨️ Typing indicators tell people you are either typing or overthinking.",
  "🤫 Silent typing hides your typing indicator. Sneaky, but legal.",
  "📩 Mute DMs when peace is required — right-click a DM in the sidebar.",
  "🔕 Muting a chat suppresses its sounds and notification badges.",
  "🔒 Group chats have a shareable join code under the chat header.",
  "🏆 Leader badges show who runs each group chat.",
  "✨ Use **bold** and *italic* formatting in your messages.",
  "💾 Drafts are saved automatically when you switch chats.",
  "⬇️ If you scroll up, click Jump to Latest to return to the present.",
  "🧾 Unread dividers show exactly where the drama started.",
  "🛡️ Keep personal info out of chats. This is a fun community tool, not a vault.",
  "🔐 Do not share passwords, addresses, phone numbers, or private details here.",
  "🎨 Try Dark, OLED, Midnight, Warm, or Daylight themes in settings.",
  "🌈 Banner colors on profiles are fully customizable in settings.",
  "🖼️ Use a direct image URL as your profile photo — any size works.",
  "⏰ Hover over a message timestamp to see exactly when it was sent.",
  "🤝 Mutual friends are shown on profile cards.",
  "📱 Static Chat works great on mobile browsers too.",
  "🧠 Your settings sync across devices automatically.",

  // Slash command tips
  "🎱 Try /8ball followed by a question for a totally scientific answer.",
  "🪙 /coinflip decides tough choices with maximum drama and minimum responsibility.",
  "🎲 /roll is RNG with better branding.",
  "🎯 /tod gives truth or dare. Use responsibly. Or at least amusingly.",
  "😂 /joke gives you a joke. Quality may vary. Confidence will not.",
  "🛳️ /ship <user1> <user2> tests compatibility. The math is legally suspicious.",
  "💡 /tip shares a random tip in chat. Wisdom for the group.",
  "📖 /quote drops a random quote into the conversation.",
  "📋 Type /help to see all available commands.",
  "✨ Use **bold** and *italic* formatting when plain text is not dramatic enough.",
  "💻 `code formatting` makes normal words feel technical.",

  // Loading quotes / funny meta tips
  "Loading friendship particles...",
  "Reticulating group chats...",
  "Calculating who left you on read...",
  "Applying suspiciously smooth animations...",
  "Teaching buttons how to button...",
  "Polishing pixels nobody will notice...",
  "Convincing Firebase to behave...",
  "Searching for the missing semicolon...",
  "Downloading more vibes...",
  "Warming up the message goblin...",
  "Loading absolutely nothing important...",
  "Synchronizing chaos...",
  "Asking the server nicely...",
  "Pretending this loading screen is useful...",
  "Adding one more feature. Definitely the last one.",
  "This tip is here because loading bars get lonely.",
  "If this takes too long, blame the Wi-Fi. It is tradition.",
  "Do not refresh. Unless refreshing fixes it. Then refresh.",
  "The app is thinking. Please respect its privacy.",
  "Loading... emotionally.",
  "Buffering friendship...",
  "Counting unread messages and bad decisions...",
  "Preparing the profile popouts...",
  "Applying Discord-ish vibes without becoming Discord.",
  "Mixing Static energy with chat energy...",
  "Installing invisible bug spray...",
  "Making sure the send button sends.",
  "Checking if 'brb' still means anything.",
  "Updating the status of people who forgot they exist.",
  "Generating fake confidence...",
  "Loading the part where everything works.",
  "Compressing drama...",
  "Uncompressing drama...",
  "Waiting for someone to type 'ok'.",
  "Spinning up the chat hamster wheel...",
  "Making usernames slightly more clickable...",
  "Counting emojis. Some of them are suspicious.",
  "Teaching avatars how to be round.",
  "Rebuilding the sidebar out of pure vibes.",
  "Almost there. Probably.",
  "Still loading, but with style.",
  "This loading screen has seen things.",
  "If you can read this, the loading tip loaded.",
  "Turning bugs into future patch notes...",
  "Summoning the GIF picker...",
  "Feeding the notification gremlin...",
  "Message history is just archaeology with screenshots.",
  "Your draft is safe. Your spelling is between you and autocorrect.",
  "Group chats are just side quests with witnesses.",
  "A watched loading bar never boils.",
  "Static Chat is loading faster than your homework motivation.",
  "If the app breaks, it was a social experiment.",
  "The pixels are unionizing.",
  "Loading screen tip: loading screen tips are usually not helpful.",
  "You are now breathing manually.",
  "You are now blinking manually.",
  "Your tongue is aware of its position. Sorry.",
  "Wi-Fi is just invisible spaghetti.",
  "The cloud is someone else's computer having a day.",
  "A bug is just a feature wearing a disguise.",
  "If it works, do not touch it. If it doesn't, touch everything.",
  "The console knows what you did.",
  "404 motivation not found.",
  "Skill issue? Maybe. Server issue? Also maybe.",
  "The best feature is the one that does not break.",
  "This app contains 0 percent actual Discord.",
  "Discord at home, but with personality.",
  "Your messages are loading. Your patience is rendering.",
  "Loading friendship data from the friendship dimension...",
  "Reading chat history like ancient scrolls...",
  "Generating perfectly normal online behavior...",
  "Making the mute button emotionally available...",
  "Remember: deleting a message does not delete the memory.",
  "Pinned messages are just messages with main-character energy.",
  "Profile banners: because rectangles deserve expression.",
  "Statuses are just tiny mood billboards.",
  "Invisible users are online in spirit.",
  "DND means Do Not Disturb, not Definitely Needs Drama.",
  "Typing indicators expose hesitation in real time.",
  "Emoji reactions: for when typing is too expensive.",
  "The GIF picker is legally a chaos engine.",
  "If the chat is quiet, someone is probably typing an essay.",
  "Every group chat has one person who changes the name too much.",
  "Muted chats are still talking. You just stopped listening.",
  "The archive is not deletion. It is the basement.",
  "Copying a message ID makes you feel like a detective.",
  "Reports work better when they include context, not just 'HELP'.",
  "Do not send private info. The internet has a long memory.",
  "If someone says 'trust me bro,' consider not doing that.",
  "Never share your password, even if the message has sparkles.",
  "The safest secret is the one you do not type.",
  "A good UI explains itself. A bad UI becomes a tutorial.",
  "Buttons should look clickable. Revolutionary.",
  "Icons are tiny pictures with big responsibilities.",
  "Rounded corners increase happiness by 6 percent.",
  "Animations should be smooth, not theatrical.",
  "Loading screens should distract you from waiting. This one is trying.",

  // Extra funny chat/community quotes
  "Someone is typing... probably a single 'ok'.",
  "A group chat without chaos is just a meeting.",
  "Every chat has a lore keeper.",
  "Every friend group has one person who sends 12 messages instead of 1.",
  "Some messages age like milk. Pin carefully.",
  "If someone says 'quick question,' prepare for a questline.",
  "The word 'soon' has no legal meaning.",
  "The phrase 'one sec' can mean anything.",
  "Typing indicators are emotional spoilers.",
  "Deleting a message after everyone saw it is performance art.",
  "Editing a message to fix a typo means the typo won.",
  "The best comeback arrives 4 hours too late.",
  "Every profile bio is either too serious or not serious enough.",
  "A status is just a tiny billboard for your current nonsense.",
  "The online dot is watching.",
  "Invisible mode: online, but in stealth.",
  "DND mode: social battery at 1 percent.",
  "Idle mode: body present, brain loading.",
  "Online mode: available for chaos.",
  "A muted chat still believes in itself.",
  "Pinned chats are VIP chaos.",
  "Unread badges multiply in darkness.",
  "A copied message ID is a tiny evidence bag.",
  "The report system appreciates complete sentences.",
  "Do not start drama before the app finishes loading.",
  "If you are confused, blame the UI. Then improve it.",
  "Profile customization is cheaper than therapy.",
  "If your friends cannot find you, check your username.",
  "If you cannot find your friends, check your spelling.",
  "Silence in chat is either peace or plotting.",
  "Pinned messages are the group chat fridge magnets.",
  "Unread messages multiply when ignored.",
  "Never underestimate a bored group chat.",
  "If the app looks different, someone probably improved it.",
  "If the app looks broken, someone probably improved it.",
  "The difference between a feature and a bug is confidence.",
  "Loading screens are just apps saying 'one sec'.",
  "The fastest message is the one you regret.",
  "Drafts are where messages go to think.",
  "Words are hard. Emojis are round.",
  "If the GIF does not embed, the GIF has chosen violence.",
  "Ctrl+F finds messages. It cannot find meaning.",
  "Pin responsibly.",
  "Mute irresponsibly. Peace matters.",
  "If you see this twice, congratulations on RNG.",
  "Some quotes are filler. This one is honest.",
  "The app is not sentient. Yet.",
  "The loading bar is trying its best.",
  "This project is for fun. Fun is allowed.",
  "Use the Suggestions tab before yelling at the screen.",
  "Your future self wants better logs.",
  "A clean UI fixes 40 percent of confusion and 0 percent of math homework.",

  // Silly obvious facts
  "Water is wet in most situations.",
  "Most chairs are optimized for sitting.",
  "The floor is usually below you.",
  "If you drop something, gravity will file the paperwork.",
  "Fire is hot. Multiple sources confirm this.",
  "Clouds are not solid. Do not attempt parkour.",
  "The sun is bright. Do not challenge it.",
  "Doors open better when you use the correct side.",
  "Breathing is a recommended daily activity.",
  "Blinking is free eye maintenance.",
  "Sleep is the human loading screen.",
  "Naps are fast travel for tired people.",
  "Socks come in pairs until laundry happens.",
  "Microwaves beep because silence was too peaceful.",
  "Hot water is aggressive water.",
  "Ice is water with commitment issues.",
  "Coffee is bean soup with social approval.",
  "Cereal is technically breakfast soup. Do not argue here.",
  "A sandwich is just edible architecture.",
  "Pizza is a circle cut into triangles inside a square box. Society accepts this.",
  "Running makes you arrive faster and tired-er.",
  "Walking long enough usually puts you somewhere else.",
  "Birds do not pay rent.",
  "Air is free while supplies last.",
  "Time flies but refuses to land.",
  "Friends are NPCs with better dialogue.",
  "Music makes silence jealous.",
  "Ceilings are floors for spiders.",
  "Windows are TVs for outside.",
  "Hallways are just stretched rooms.",
  "Laundry is where socks enter witness protection.",
  "Dishes are a tower defense game and the sink is losing.",
  "Homework does not drop legendary loot.",
  "Group projects are stealth games with worse teammates.",
  "Pop quizzes are jump scares with pencils.",
  "Lunch is the school-approved speedrun.",
  "Study breaks cannot fail if they never end.",

  // Gaming-style tips
  "The tutorial is optional until it is not.",
  "Red things are not always enemies, but they are suspicious.",
  "You cannot win if you lose. Think about it.",
  "Try not dying. It helps a lot.",
  "Jumping is faster. Probably.",
  "The walls exist for a reason.",
  "If you cannot find the exit, maybe you are the exit.",
  "Saving prevents tragedy. Usually.",
  "Friendly fire is only funny once.",
  "Do not jump off the map. It is not a shortcut.",
  "Loot everything. Especially if you do not need it.",
  "The harder the level, the louder the keyboard.",
  "Double jump only works if the game agrees.",
  "Explosions solve problems and create new ones.",
  "Crouching in real life does not increase stealth.",
  "The final boss does not care about your feelings.",
  "The game is not cheating. You are losing correctly.",
  "Lag is just the universe taking a break.",
  "If it glows, click it. If it explodes, remember that.",
  "Checkpoint flags appreciate being noticed.",
  "Collect coins. They will not improve your real finances.",
  "Taking fall damage? Try falling less.",
  "If the drop rate is 1 percent, expect 0 percent today.",
  "Randomness is fairness wearing a clown nose.",
  "Pressing W moves you forward in-game and emotionally.",
  "Pressing Space is legally considered optimism.",
  "Pressing Escape does not delete real life.",
  "Pressing Enter sends the message. Choose your words before the rectangle does.",
  "Yelling at the microwave does not make it faster.",
  "Yelling at Wi-Fi does not make it stronger, but it feels correct.",
  "No one has ever won an argument with Wi-Fi.",
  "The router is innocent until proven unplugged.",

  // Achievement-style
  "Achievement unlocked: Read the loading tip.",
  "Achievement locked: Touch grass.",
  "Achievement hidden: Found the same bug twice.",
  "Achievement pending: Made a good group chat name.",
  "Achievement complete: Opened settings and changed nothing.",
  "Achievement complete: Stared at the typing indicator.",
  "Achievement complete: Used /coinflip to avoid responsibility.",
  "Achievement complete: Sent a GIF instead of explaining.",
  "Achievement complete: Muted the loudest chat.",
  "Achievement complete: Pinned the only useful message.",
  "Achievement complete: Survived beta.",
  "Achievement complete: Favorited your first GIF.",
];

/** Returns a random tip string. */
export function getRandomTip() {
  return LOADING_TIPS[Math.floor(Math.random() * LOADING_TIPS.length)];
}
